name: Tests

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
<<<<<<< HEAD
        python-version: ["3.8","3.9", "3.10"]
        
=======
        python-version: ["3.11"]

>>>>>>> 1036107ec990f210699798380cd3fbff1db13baa
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python all python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Runs Test
        run: python -m unittest test.py
